# Generated by Django 5.1.1 on 2024-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_game_buyer_alter_game_age_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=500, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=10),
        ),
    ]
