# Generated by Django 5.1.1 on 2024-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_bayer_balance_game_cost_game_description_game_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayer',
            name='age',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
